// This file is auto-generated by @hey-api/openapi-ts

import { UUID } from "crypto";

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type EmpCreate = {
    workemail: string;
    name?: string;
    address?: (string | null);
    mobile_number?: string;
};

export type EmpPublic = {
    workemail: string;
    name?: string ;
    address?: (string | null);
    mobile_number?: string;
    empcode: UUID;
    emp_id: UUID;
    created_at?: (string | null);
};

export type EmpsPublic = {
    data: Array<EmpPublic>;
    count: number;
};

export type EmpUpdate = {
    workemail: string;
    name?: (string | null);
    address?: (string | null);
    mobile_number?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type DepCreate = {
    dep_name: string;
    dep_code: string;
};

export type DepPublic = {
    dep_name: string;
    dep_code: string;
    dep_id: UUID;
    created_at?: (string | null);
};

export type DepUpdate = {
    dep_name?: (string | null);
    dep_code?: (string | null);
};

export type DepsPublic = {
    data: Array<DepPublic>;
    count: number;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type EmpsReadEmpsData = {
    limit?: number;
};

export type EmpsReadEmpsResponse = (EmpsPublic);

export type EmpsCreateEmpData = {
    requestBody: EmpCreate;
};

export type EmpsCreateEmpResponse = (EmpPublic);

export type EmpsReadEmpData = {
    empId: string;
};

export type EmpsReadEmpResponse = (EmpPublic);

export type EmpsUpdateEmpData = {
    empId: string;
    requestBody: EmpUpdate;
};

export type EmpsUpdateEmpResponse = (EmpPublic);

export type EmpsDeleteEmpData = {
    empId: string;
};

export type EmpsDeleteEmpResponse = (Message);

export type DepsReadDepsData = {
    skip?: number;
    limit?: number;
};

export type DepsReadDepsResponse = (DepsPublic);

export type DepsCreateDepData = {
    requestBody: DepCreate;
};

export type DepsCreateDepResponse = (DepPublic);

export type DepsReadDepData = {
    skip: number;
    depId: string;
};

export type DepsReadDepResponse = (DepPublic);

export type DepsUpdateDepData = {
    depId: string;
    requestBody: DepUpdate;
};

export type DepsUpdateDepResponse = (DepPublic);

export type DepsDeleteDepData = {
    depId: string;
};

export type DepsDeleteDepResponse = (Message);


export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);