"""dep

Revision ID: 022dcdaf0f3d
Revises: 5aa8acb20b5a
Create Date: 2026-02-13 13:29:01.716464

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '022dcdaf0f3d'
down_revision = '5aa8acb20b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dep', sa.Column('dep_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False))
    op.drop_column('dep', 'Depname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dep', sa.Column('Depname', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('dep', 'dep_name')
    # ### end Alembic commands ###
