"""dep

Revision ID: 19333854f565
Revises: 022dcdaf0f3d
Create Date: 2026-02-13 14:16:18.754701

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '19333854f565'
down_revision = '022dcdaf0f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dep', 'depcode',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dep', 'depcode',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
