"""dep

Revision ID: 40c690714ff2
Revises: 9bc5b107f3a4
Create Date: 2026-02-13 13:20:09.931818

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '40c690714ff2'
down_revision = '9bc5b107f3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dep',
    sa.Column('Depname', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('depcode', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dep_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dep_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('depcode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dep')
    # ### end Alembic commands ###
