"""dep

Revision ID: 5aa8acb20b5a
Revises: 40c690714ff2
Create Date: 2026-02-13 13:24:26.663111

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5aa8acb20b5a'
down_revision = '40c690714ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
