"""add dep_name to emp

Revision ID: 5f2b8bb8e6d3
Revises: d7751a94a713
Create Date: 2026-02-17 11:28:37.598882

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5f2b8bb8e6d3'
down_revision = 'd7751a94a713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emp', sa.Column('dep_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('emp', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emp', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('emp', 'dep_name')
    # ### end Alembic commands ###
