"""depempnew

Revision ID: 69ae252b58f6
Revises: da97ef1deeca
Create Date: 2026-02-16 11:25:01.534259

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '69ae252b58f6'
down_revision = 'da97ef1deeca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emp', sa.Column('depemp_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'emp', 'dep', ['depemp_id'], ['dep_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emp', type_='foreignkey')
    op.drop_column('emp', 'depemp_id')
    # ### end Alembic commands ###
