"""dep

Revision ID: 8861bcdd59bb
Revises: 9bc5b107f3a4
Create Date: 2026-02-13 16:31:26.747211

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8861bcdd59bb'
down_revision = '9bc5b107f3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dep',
    sa.Column('dep_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('dep_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('dep_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('depuserid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['depuserid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dep_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dep')
    # ### end Alembic commands ###
