"""emp

Revision ID: 9bc5b107f3a4
Revises: e9e101715e22
Create Date: 2026-02-12 11:35:13.885227

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9bc5b107f3a4'
down_revision = 'e9e101715e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
