"""init

Revision ID: c009a4285ae1
Revises: fe56fa70289e
Create Date: 2026-02-11 15:24:32.604391

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c009a4285ae1'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emp',
    sa.Column('workemail', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('mobile_number', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('empcode', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emp_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('empcode')
    )
    op.create_index(op.f('ix_emp_workemail'), 'emp', ['workemail'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emp_workemail'), table_name='emp')
    op.drop_table('emp')
    # ### end Alembic commands ###
