"""EMP

Revision ID: c4aec2ea7c5c
Revises: 6ce33e932aaa
Create Date: 2026-02-11 16:52:06.592287

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c4aec2ea7c5c'
down_revision = '6ce33e932aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
