"""depempnew2

Revision ID: d7751a94a713
Revises: ee7c05c1a555
Create Date: 2026-02-16 14:04:36.488389

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd7751a94a713'
down_revision = 'ee7c05c1a555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
