"""depemp

Revision ID: da97ef1deeca
Revises: 7d5fdee5c2ee
Create Date: 2026-02-16 11:20:49.289089

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'da97ef1deeca'
down_revision = '7d5fdee5c2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emp', sa.Column('depemp_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'emp', 'dep', ['depemp_id'], ['dep_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emp', type_='foreignkey')
    op.drop_column('emp', 'depemp_id')
    # ### end Alembic commands ###
