"""init

Revision ID: e058f01e7a61
Revises: c4aec2ea7c5c
Create Date: 2026-02-12 09:53:33.058424

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e058f01e7a61'
down_revision = 'c4aec2ea7c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
