"""deppartment

Revision ID: ee7c05c1a555
Revises: fc8a91bf6760
Create Date: 2026-02-16 13:17:28.458486

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ee7c05c1a555'
down_revision = 'fc8a91bf6760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dep', 'depemp_id')
    op.add_column('emp', sa.Column('dep_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emp', 'dep_name')
    op.add_column('dep', sa.Column('depemp_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
