"""depempnew

Revision ID: fc8a91bf6760
Revises: 9e5e79e836d6
Create Date: 2026-02-16 11:38:05.977804

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fc8a91bf6760'
down_revision = '9e5e79e836d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dep', sa.Column('depemp_id', sa.Uuid(), nullable=True))
    op.add_column('emp', sa.Column('depemp_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'emp', 'dep', ['depemp_id'], ['dep_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emp', type_='foreignkey')
    op.drop_column('emp', 'depemp_id')
    op.drop_column('dep', 'depemp_id')
    # ### end Alembic commands ###
